apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: reboot-uam
type: Opaque
stringData:
  root-password: reboot-root
  uam-password: reboot-uam
  auth-password: reboot-auth
  workflow-password: reboot-workflow
  audit-password: reboot-audit
