spring:
  application:
    name: reboot-workflow-service
  datasource:
    url: jdbc:mariadb://localhost:3306/uam_workflow
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    schemas: uam_workflow

server:
  port: 8083
