apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  namespace: reboot-uam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service
          image: reboot/audit-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: audit-service-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: audit-password
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
